select * from customer limit 20

ALTER TABLE customer
RENAME COLUMN "customer id" TO customer_id;
ALTER TABLE customer
RENAME COLUMN "purchase amount (usd)" TO purchase_amount;
ALTER TABLE customer
RENAME COLUMN "item purchased" TO item_purchased;
ALTER TABLE customer
RENAME COLUMN "review rating" TO review_rating;
ALTER TABLE customer
RENAME COLUMN "subscription status" TO subscription_status;
ALTER TABLE customer
RENAME COLUMN "shipping type" TO shipping_type;
ALTER TABLE customer
RENAME COLUMN "discount applied" TO discount_applied;
ALTER TABLE customer
RENAME COLUMN "promo code used" TO promo_code_used;
ALTER TABLE customer
RENAME COLUMN "previous purchases" TO previous_purchases;
ALTER TABLE customer
RENAME COLUMN "payment method" TO payment_method;
ALTER TABLE customer
RENAME COLUMN "frequency of purchases" TO frequency_of_purchases;

--SQL Business Questions:
--Q1. What is the total revenue generated by each product category?
SELECT gender,SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >(SELECT AVG(purchase_amount)FROM customer);
  
--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(avg(review_rating::numeric),2) as "Average product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

--Q4. Compare the average purchase amount between Standards and Express Shipping.
select shipping_type,ROUND(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id)as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100* sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show average spend for each segment.
with customer_type as (
select customer_id, previous_purchases,
case
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id)as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) more likely to subscribe?
select subscription_status,count(customer_id)as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status 
--Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;
